name: Elixir CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.14.2"
          otp-version: "24.1"
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
