name: Elixir CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  MIX_ENV: test

jobs:
  build:
    name: Build and test
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        elixir: [1.14.2]
        otp: [25]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          experimental-otp: true
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
